import '../models/metro_station.dart';

/// Repository providing static coordinates and metadata for all Kolkata Metro Stations
class MetroRepository {
  MetroRepository._();
  static final MetroRepository instance = MetroRepository._();

  static const List<MetroStation> allStations = [
    // --- Line 1 (Blue Line: North-South) ---
    MetroStation(
      id: 'm_dakshineswar',
      name: 'Dakshineswar',
      line: KolkataMetroLine.blue,
      latitude: 22.6536,
      longitude: 88.3582,
      popularPandalsNearby: ['Dakshineswar Kali Temple', 'Ariadaha Sarbojanin'],
    ),
    MetroStation(
      id: 'm_baranagar',
      name: 'Baranagar',
      line: KolkataMetroLine.blue,
      latitude: 22.6416,
      longitude: 88.3697,
      popularPandalsNearby: ['Baranagar Netaji Colony', 'Bonhooghly Sarbojanin'],
    ),
    MetroStation(
      id: 'm_noapara',
      name: 'Noapara',
      line: KolkataMetroLine.blue,
      latitude: 22.6375,
      longitude: 88.3847,
    ),
    MetroStation(
      id: 'm_dumdum',
      name: 'Dum Dum',
      line: KolkataMetroLine.blue,
      latitude: 22.6217,
      longitude: 88.3789,
      popularPandalsNearby: ['Dum Dum Park Bharat Chakra', 'Dum Dum Park Tarun Sangha'],
    ),
    MetroStation(
      id: 'm_belgachia',
      name: 'Belgachia',
      line: KolkataMetroLine.blue,
      latitude: 22.6049,
      longitude: 88.3813,
      popularPandalsNearby: ['Tala Barowari', 'Sreebhumi Sporting Club'],
    ),
    MetroStation(
      id: 'm_shyambazar',
      name: 'Shyambazar',
      line: KolkataMetroLine.blue,
      latitude: 22.5997,
      longitude: 88.3712,
      popularPandalsNearby: [
        'Nalin Sarkar Street',
        'Hatibagan Sarbojanin',
        'Bagbazar Sarbojanin',
        'Kasi Bose Lane',
      ],
    ),
    MetroStation(
      id: 'm_shobhabazar',
      name: 'Shobhabazar Sutanuti',
      line: KolkataMetroLine.blue,
      latitude: 22.5925,
      longitude: 88.3653,
      popularPandalsNearby: [
        'Kumartuli Park',
        'Sovabazar Rajbari',
        'Ahiritola Sarbojanin',
        'Beniatola',
      ],
    ),
    MetroStation(
      id: 'm_girish_park',
      name: 'Girish Park',
      line: KolkataMetroLine.blue,
      latitude: 22.5855,
      longitude: 88.3606,
      popularPandalsNearby: ['Vivekananda Sporting', 'Simla Byayam Samiti', 'Pathuriaghata'],
    ),
    MetroStation(
      id: 'm_mg_road',
      name: 'Mahatma Gandhi Road (MG Road)',
      line: KolkataMetroLine.blue,
      latitude: 22.5794,
      longitude: 88.3605,
      popularPandalsNearby: ['Mohammad Ali Park', 'College Square'],
    ),
    MetroStation(
      id: 'm_central',
      name: 'Central',
      line: KolkataMetroLine.blue,
      latitude: 22.5714,
      longitude: 88.3592,
      popularPandalsNearby: ['Santosh Mitra Square (Lebutala)', 'Bowbazar'],
    ),
    MetroStation(
      id: 'm_chandni_chowk',
      name: 'Chandni Chowk',
      line: KolkataMetroLine.blue,
      latitude: 22.5663,
      longitude: 88.3556,
      popularPandalsNearby: ['Chandni Sarbojanin', 'Wellington Square'],
    ),
    MetroStation(
      id: 'm_esplanade',
      name: 'Esplanade',
      line: KolkataMetroLine.blue,
      latitude: 22.5647,
      longitude: 88.3516,
      isInterchange: true,
      connectingLines: [KolkataMetroLine.green],
      popularPandalsNearby: ['New Market', 'Janbazar Durgotsav', 'Dharmatala'],
    ),
    MetroStation(
      id: 'm_park_street',
      name: 'Park Street',
      line: KolkataMetroLine.blue,
      latitude: 22.5529,
      longitude: 88.3513,
      popularPandalsNearby: ['Park Circus Sarbojanin', 'Ripon Street'],
    ),
    MetroStation(
      id: 'm_maidan',
      name: 'Maidan',
      line: KolkataMetroLine.blue,
      latitude: 22.5447,
      longitude: 88.3497,
      popularPandalsNearby: ['Victoria Memorial Ambiance', 'Red Road Carnival'],
    ),
    MetroStation(
      id: 'm_rabindra_sadan',
      name: 'Rabindra Sadan',
      line: KolkataMetroLine.blue,
      latitude: 22.5372,
      longitude: 88.3475,
      popularPandalsNearby: ['Gokhale Road', 'Chowringhee Sarbojanin'],
    ),
    MetroStation(
      id: 'm_netaji_bhavan',
      name: 'Netaji Bhavan',
      line: KolkataMetroLine.blue,
      latitude: 22.5311,
      longitude: 88.3467,
      popularPandalsNearby: ['Padmapukur Youth', 'Chakraberia Sarbojanin'],
    ),
    MetroStation(
      id: 'm_jatin_das_park',
      name: 'Jatin Das Park',
      line: KolkataMetroLine.blue,
      latitude: 22.5222,
      longitude: 88.3472,
      popularPandalsNearby: ['Maddox Square', 'Ballygunge Cultural', 'Deshapriya Park'],
    ),
    MetroStation(
      id: 'm_kalighat',
      name: 'Kalighat',
      line: KolkataMetroLine.blue,
      latitude: 22.5158,
      longitude: 88.3464,
      popularPandalsNearby: [
        'Deshapriya Park',
        'Tridhara Sammilani',
        'Ekdalia Evergreen',
        'Singhi Park',
        'Badamtala Ashar Sangha',
        'Chetla Agrani',
      ],
    ),
    MetroStation(
      id: 'm_rabindra_sarobar',
      name: 'Rabindra Sarobar',
      line: KolkataMetroLine.blue,
      latitude: 22.5081,
      longitude: 88.3456,
      popularPandalsNearby: ['Mudiali Club', 'Shiv Mandir', 'Suruchi Sangha'],
    ),
    MetroStation(
      id: 'm_uttam_kumar',
      name: 'Mahanayak Uttam Kumar (Tollygunge)',
      line: KolkataMetroLine.blue,
      latitude: 22.4975,
      longitude: 88.3450,
      popularPandalsNearby: ['Babubagan Club', 'Selimpur Club', 'Jodhpur Park'],
    ),
    MetroStation(
      id: 'm_netaji_kudghat',
      name: 'Netaji (Kudghat)',
      line: KolkataMetroLine.blue,
      latitude: 22.4856,
      longitude: 88.3461,
      popularPandalsNearby: ['Kudghat Pragati Sangha', 'Ashok Nagar Sarbojanin'],
    ),
    MetroStation(
      id: 'm_masterda_surya_sen',
      name: 'Masterda Surya Sen (Bansdroni)',
      line: KolkataMetroLine.blue,
      latitude: 22.4764,
      longitude: 88.3533,
    ),
    MetroStation(
      id: 'm_gitanjali',
      name: 'Gitanjali (Naktala)',
      line: KolkataMetroLine.blue,
      latitude: 22.4703,
      longitude: 88.3622,
      popularPandalsNearby: ['Naktala Udayan Sangha'],
    ),
    MetroStation(
      id: 'm_kavi_nazrul',
      name: 'Kavi Nazrul (Garia Bazar)',
      line: KolkataMetroLine.blue,
      latitude: 22.4636,
      longitude: 88.3736,
      popularPandalsNearby: ['Garia Navadurga', 'Kanungo Park'],
    ),
    MetroStation(
      id: 'm_shahid_khudiram',
      name: 'Shahid Khudiram (Briji)',
      line: KolkataMetroLine.blue,
      latitude: 22.4572,
      longitude: 88.3886,
    ),
    MetroStation(
      id: 'm_kavi_subhash',
      name: 'Kavi Subhash (New Garia)',
      line: KolkataMetroLine.blue,
      latitude: 22.4589,
      longitude: 88.3986,
      isInterchange: true,
      connectingLines: [KolkataMetroLine.orange],
    ),

    // --- Line 2 (Green Line: East-West / Underwater Metro) ---
    MetroStation(
      id: 'm_howrah_maidan',
      name: 'Howrah Maidan',
      line: KolkataMetroLine.green,
      latitude: 22.5856,
      longitude: 88.3242,
      popularPandalsNearby: ['Howrah Sammilani', 'Mallick Phatak'],
    ),
    MetroStation(
      id: 'm_howrah_station',
      name: 'Howrah Railway Station Metro',
      line: KolkataMetroLine.green,
      latitude: 22.5847,
      longitude: 88.3431,
      popularPandalsNearby: ['Howrah Station Circular', 'Golabari Ghat'],
    ),
    MetroStation(
      id: 'm_mahakaran',
      name: 'Mahakaran (BBD Bagh)',
      line: KolkataMetroLine.green,
      latitude: 22.5739,
      longitude: 88.3494,
      popularPandalsNearby: ['Lalbazar', 'Burrabazar Barowari'],
    ),
    MetroStation(
      id: 'm_sealdah',
      name: 'Sealdah Railway Station Metro',
      line: KolkataMetroLine.green,
      latitude: 22.5672,
      longitude: 88.3711,
      popularPandalsNearby: ['Sealdah Athletic Club', 'Santosh Mitra Square', 'Chaltabagan'],
    ),
    MetroStation(
      id: 'm_phoolbagan',
      name: 'Phoolbagan',
      line: KolkataMetroLine.green,
      latitude: 22.5703,
      longitude: 88.3931,
      popularPandalsNearby: ['Maniktala Chaltabagan Lohapatty', 'Beleghata Sandhani'],
    ),
    MetroStation(
      id: 'm_saltlake_stadium',
      name: 'Salt Lake Stadium',
      line: KolkataMetroLine.green,
      latitude: 22.5706,
      longitude: 88.4042,
      popularPandalsNearby: ['Kadapara Durgotsav', 'Subhas Sarobar'],
    ),
    MetroStation(
      id: 'm_bengal_chemical',
      name: 'Bengal Chemical',
      line: KolkataMetroLine.green,
      latitude: 22.5772,
      longitude: 88.4069,
      popularPandalsNearby: ['Salt Lake Duttabad', 'Kakurgachi Yubak Vrinda'],
    ),
    MetroStation(
      id: 'm_city_centre',
      name: 'City Centre (Salt Lake)',
      line: KolkataMetroLine.green,
      latitude: 22.5878,
      longitude: 88.4097,
      popularPandalsNearby: ['Salt Lake Block BJ', 'Salt Lake Block FD'],
    ),
    MetroStation(
      id: 'm_central_park',
      name: 'Central Park (Karunamoyee)',
      line: KolkataMetroLine.green,
      latitude: 22.5872,
      longitude: 88.4194,
      popularPandalsNearby: ['Salt Lake Mela Ground', 'Salt Lake FD Block'],
    ),
    MetroStation(
      id: 'm_karunamoyee',
      name: 'Karunamoyee',
      line: KolkataMetroLine.green,
      latitude: 22.5833,
      longitude: 88.4239,
      popularPandalsNearby: ['Salt Lake AJ Block', 'Salt Lake BJ Block'],
    ),
    MetroStation(
      id: 'm_sector_v',
      name: 'Salt Lake Sector V',
      line: KolkataMetroLine.green,
      latitude: 22.5786,
      longitude: 88.4319,
      popularPandalsNearby: ['College More Technology Hub', 'New Town Gateway'],
    ),

    // --- Line 3 (Purple Line: Joka-Majerhat) ---
    MetroStation(
      id: 'm_majerhat',
      name: 'Majerhat',
      line: KolkataMetroLine.purple,
      latitude: 22.5208,
      longitude: 88.3242,
      popularPandalsNearby: ['Alipore Mint', 'Chetla Agrani (West Entry)'],
    ),
    MetroStation(
      id: 'm_taratala',
      name: 'Taratala',
      line: KolkataMetroLine.purple,
      latitude: 22.5103,
      longitude: 88.3181,
      popularPandalsNearby: ['Behala Club', 'Taratala Sarbojanin'],
    ),
    MetroStation(
      id: 'm_behala_chowrasta',
      name: 'Behala Chowrasta',
      line: KolkataMetroLine.purple,
      latitude: 22.4922,
      longitude: 88.3117,
      popularPandalsNearby: ['Behala Nutan Dal', 'Barisha Club', 'Behala Friends'],
    ),

    // --- Line 6 (Orange Line: Ruby Corridor) ---
    MetroStation(
      id: 'm_hemanta_mukhopadhyay',
      name: 'Hemanta Mukhopadhyay (Ruby)',
      line: KolkataMetroLine.orange,
      latitude: 22.5133,
      longitude: 88.4014,
      popularPandalsNearby: ['Ruby Hospital Crossing', 'Kasba Bosepukur Sitala Mandir'],
    ),
  ];

  List<MetroStation> searchStations(String query) {
    if (query.trim().isEmpty) return allStations;
    final clean = query.trim().toLowerCase();
    return allStations.where((s) {
      final name = s.name.toLowerCase();
      final lineName = s.line.label.toLowerCase();
      final nearby = s.popularPandalsNearby.any((p) => p.toLowerCase().contains(clean));
      return name.contains(clean) || lineName.contains(clean) || nearby;
    }).toList();
  }
}
