import 'package:latlong2/latlong.dart';
import '../models/metro_station.dart';

/// Repository providing accurate coordinates, station topology, and metadata
/// for all 55 Kolkata Metro stations across 5 operational lines.
class MetroRepository {
  MetroRepository._();
  static final MetroRepository instance = MetroRepository._();

  /// Comprehensive directory of all 55 unique operational Kolkata Metro Stations.
  static const List<MetroStation> allStations = [
    // ==========================================
    // --- Line 1: Blue Line (North-South Corridor) ---
    // ==========================================
    MetroStation(
      id: 'dakshineswar',
      name: 'Dakshineswar',
      nameBn: 'দক্ষিণেশ্বর',
      code: 'KDSW',
      line: KolkataMetroLine.blue,
      latitude: 22.653971,
      longitude: 88.363724,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Sri Ramakrishna', 'm_dakshineswar'],
      popularPandalsNearby: ['Dakshineswar Kali Temple', 'Ariadaha Sarbojanin'],
    ),
    MetroStation(
      id: 'baranagar',
      name: 'Baranagar',
      nameBn: 'বরাহনগর',
      code: 'KBAR',
      line: KolkataMetroLine.blue,
      latitude: 22.653529,
      longitude: 88.378873,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['m_baranagar'],
      popularPandalsNearby: ['Baranagar Netaji Colony', 'Bonhooghly Sarbojanin'],
    ),
    MetroStation(
      id: 'noapara',
      name: 'Noapara',
      nameBn: 'নোয়াপাড়া',
      code: 'KNAP',
      line: KolkataMetroLine.blue,
      latitude: 22.63972,
      longitude: 88.39389,
      layout: 'Elevated',
      isInterchange: true,
      connectingLines: [KolkataMetroLine.yellow],
      aliases: ['Maa Sarada', 'm_noapara'],
      popularPandalsNearby: ['Noapara Sarbojanin', 'Dunlop Junction Pujo'],
    ),
    MetroStation(
      id: 'dum-dum',
      name: 'Dum Dum',
      nameBn: 'দমদম',
      code: 'KDMI',
      line: KolkataMetroLine.blue,
      latitude: 22.62111,
      longitude: 88.39278,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Dumdum', 'm_dumdum', 'm_dum_dum'],
      popularPandalsNearby: ['Dum Dum Park Bharat Chakra', 'Dum Dum Park Tarun Sangha'],
    ),
    MetroStation(
      id: 'belgachhia',
      name: 'Belgachhia',
      nameBn: 'বেলগাছিয়া',
      code: 'KBEL',
      line: KolkataMetroLine.blue,
      latitude: 22.60583,
      longitude: 88.38639,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Belgachia', 'm_belgachia', 'm_belgachhia'],
      popularPandalsNearby: ['Tala Barowari', 'Sreebhumi Sporting Club (West Entry)'],
    ),
    MetroStation(
      id: 'shyambazar',
      name: 'Shyambazar',
      nameBn: 'শ্যামবাজার',
      code: 'KSHY',
      line: KolkataMetroLine.blue,
      latitude: 22.601313,
      longitude: 88.372586,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['m_shyambazar'],
      popularPandalsNearby: [
        'Nalin Sarkar Street',
        'Hatibagan Sarbojanin',
        'Bagbazar Sarbojanin',
        'Kasi Bose Lane',
      ],
    ),
    MetroStation(
      id: 'shobhabazar-sutanuti',
      name: 'Shobhabazar Sutanuti',
      nameBn: 'শোভাবাজার সুতানুটি',
      code: 'KSHO',
      line: KolkataMetroLine.blue,
      latitude: 22.596029,
      longitude: 88.365285,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Hatkhola', 'Sovabazar Sutanuti', 'Sovabazar', 'm_shobhabazar', 'm_shobhabazar_sutanuti'],
      popularPandalsNearby: [
        'Kumartuli Park',
        'Sovabazar Rajbari',
        'Ahiritola Sarbojanin',
        'Beniatola',
      ],
    ),
    MetroStation(
      id: 'girish-park',
      name: 'Girish Park',
      nameBn: 'গিরীশ পার্ক',
      code: 'KGPK',
      line: KolkataMetroLine.blue,
      latitude: 22.587143,
      longitude: 88.363083,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Jorasanko', 'm_girish_park'],
      popularPandalsNearby: ['Vivekananda Sporting', 'Simla Byayam Samiti', 'Pathuriaghata'],
    ),
    MetroStation(
      id: 'mahatma-gandhi-road',
      name: 'Mahatma Gandhi Road',
      nameBn: 'মহাত্মা গান্ধী রোড',
      code: 'KMHR',
      line: KolkataMetroLine.blue,
      latitude: 22.580858,
      longitude: 88.361401,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Mahajati Sadan', 'Chittaranjan Avenue', 'MG Road', 'm_mg_road', 'm_mahatma_gandhi_road'],
      popularPandalsNearby: ['Mohammad Ali Park', 'College Square'],
    ),
    MetroStation(
      id: 'central',
      name: 'Central',
      nameBn: 'সেন্ট্রাল',
      code: 'KCEN',
      line: KolkataMetroLine.blue,
      latitude: 22.57247,
      longitude: 88.358788,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Bepin Behari Ganguly Street', 'm_central'],
      popularPandalsNearby: ['Santosh Mitra Square (Lebutala)', 'Bowbazar Sarbojanin'],
    ),
    MetroStation(
      id: 'chandni-chowk',
      name: 'Chandni Chowk',
      nameBn: 'চাঁদনি চক',
      code: 'KCWC',
      line: KolkataMetroLine.blue,
      latitude: 22.566796,
      longitude: 88.354137,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Ganesh Chandra Avenue', 'm_chandni_chowk'],
      popularPandalsNearby: ['Chandni Sarbojanin', 'Wellington Square'],
    ),
    MetroStation(
      id: 'esplanade',
      name: 'Esplanade',
      nameBn: 'এসপ্ল্যানেড',
      code: 'KESP',
      line: KolkataMetroLine.blue,
      latitude: 22.56444,
      longitude: 88.35167,
      layout: 'Underground',
      isInterchange: true,
      connectingLines: [KolkataMetroLine.green],
      aliases: ['Dharmatala', 'm_esplanade'],
      popularPandalsNearby: ['New Market Durgotsav', 'Janbazar Durgotsav'],
    ),
    MetroStation(
      id: 'park-street',
      name: 'Park Street',
      nameBn: 'পার্ক স্ট্রীট',
      code: 'KPSK',
      line: KolkataMetroLine.blue,
      latitude: 22.555,
      longitude: 88.35028,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Mother Teresa', 'm_park_street'],
      popularPandalsNearby: ['Park Circus Sarbojanin', 'Ripon Street Durgotsav'],
    ),
    MetroStation(
      id: 'maidan',
      name: 'Maidan',
      nameBn: 'ময়দান',
      code: 'KMDI',
      line: KolkataMetroLine.blue,
      latitude: 22.54944,
      longitude: 88.34889,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Gostho Pal', 'm_maidan'],
      popularPandalsNearby: ['Victoria Memorial Ambiance', 'Red Road Carnival Zone'],
    ),
    MetroStation(
      id: 'rabindra-sadan',
      name: 'Rabindra Sadan',
      nameBn: 'রবীন্দ্র সদন',
      code: 'KRSD',
      line: KolkataMetroLine.blue,
      latitude: 22.54139,
      longitude: 88.34722,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Exide', 'm_rabindra_sadan'],
      popularPandalsNearby: ['Gokhale Road', 'Chowringhee Sarbojanin'],
    ),
    MetroStation(
      id: 'netaji-bhavan',
      name: 'Netaji Bhavan',
      nameBn: 'নেতাজি ভবন',
      code: 'KNBN',
      line: KolkataMetroLine.blue,
      latitude: 22.53333,
      longitude: 88.34611,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Bhawanipore', 'm_netaji_bhavan'],
      popularPandalsNearby: ['Bhawanipore 75 Palli', 'Bakul Bagan', 'Chakraberia Sarbojanin'],
    ),
    MetroStation(
      id: 'jatin-das-park',
      name: 'Jatin Das Park',
      nameBn: 'যতীন দাস পার্ক',
      code: 'KJPK',
      line: KolkataMetroLine.blue,
      latitude: 22.524262,
      longitude: 88.346489,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Hazra', 'm_jatin_das_park'],
      popularPandalsNearby: ['Maddox Square', 'Hazra Park Durgotsab', 'Deshapriya Park'],
    ),
    MetroStation(
      id: 'kalighat',
      name: 'Kalighat',
      nameBn: 'কালীঘাট',
      code: 'KKHG',
      line: KolkataMetroLine.blue,
      latitude: 22.516652,
      longitude: 88.346003,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Rashbehari Basu', 'm_kalighat'],
      popularPandalsNearby: [
        'Badamtala Ashar Sangha',
        '66 Pally',
        'Nepal Bhattacharjee Street Club',
        'Mudiali Club',
      ],
    ),
    MetroStation(
      id: 'rabindra-sarobar',
      name: 'Rabindra Sarobar',
      nameBn: 'রবীন্দ্র সরোবর',
      code: 'KRSB',
      line: KolkataMetroLine.blue,
      latitude: 22.50722,
      longitude: 88.34556,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Charu Market', 'Dhakuria', 'm_rabindra_sarobar'],
      popularPandalsNearby: ['Shiv Mandir', 'Mudiali Club (South Entry)', 'Tridhara Sammilani'],
    ),
    MetroStation(
      id: 'mahanayak-uttam-kumar',
      name: 'Mahanayak Uttam Kumar',
      nameBn: 'মহানায়ক উত্তম কুমার',
      code: 'KMUK',
      line: KolkataMetroLine.blue,
      latitude: 22.49472,
      longitude: 88.345,
      layout: 'At grade',
      isInterchange: false,
      aliases: ['Tollygunge', 'm_uttam_kumar', 'm_mahanayak_uttam_kumar'],
      popularPandalsNearby: ['Tollygunge Club Pujo', 'Golf Green Sarbojanin'],
    ),
    MetroStation(
      id: 'netaji',
      name: 'Netaji',
      nameBn: 'নেতাজি',
      code: 'KNTJ',
      line: KolkataMetroLine.blue,
      latitude: 22.480976,
      longitude: 88.346,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Kudghat', 'm_netaji_kudghat', 'm_netaji'],
      popularPandalsNearby: ['Kudghat Sarbojanin', 'Ranikuthi Sarbojanin'],
    ),
    MetroStation(
      id: 'masterda-surya-sen',
      name: 'Masterda Surya Sen',
      nameBn: 'মাস্টারদা সূর্য সেন',
      code: 'KMSN',
      line: KolkataMetroLine.blue,
      latitude: 22.473521,
      longitude: 88.360871,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Bansdroni', 'm_masterda_surya_sen'],
      popularPandalsNearby: ['Bansdroni Sarbojanin', 'Ushumpur Durgotsav'],
    ),
    MetroStation(
      id: 'gitanjali',
      name: 'Gitanjali',
      nameBn: 'গীতাঞ্জলি',
      code: 'KGTN',
      line: KolkataMetroLine.blue,
      latitude: 22.469426,
      longitude: 88.369985,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Naktala', 'm_gitanjali'],
      popularPandalsNearby: ['Naktala Udayan Sangha'],
    ),
    MetroStation(
      id: 'kavi-nazrul',
      name: 'Kavi Nazrul',
      nameBn: 'কবি নজরুল',
      code: 'KKNZ',
      line: KolkataMetroLine.blue,
      latitude: 22.46417,
      longitude: 88.38055,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Garia Bazar', 'm_kavi_nazrul'],
      popularPandalsNearby: ['Garia Sarbojanin', 'Baishnabghata Patuli'],
    ),
    MetroStation(
      id: 'shahid-khudiram',
      name: 'Shahid Khudiram',
      nameBn: 'শহীদ ক্ষুদিরাম',
      code: 'KSKD',
      line: KolkataMetroLine.blue,
      latitude: 22.465972,
      longitude: 88.39167,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Briji', 'Dhalai Bridge', 'm_shahid_khudiram'],
      popularPandalsNearby: ['Dhalai Bridge Sarbojanin', 'Patuli Floating Market Area'],
    ),
    MetroStation(
      id: 'kavi-subhash',
      name: 'Kavi Subhash',
      nameBn: 'কবি সুভাষ',
      code: 'KKSO',
      line: KolkataMetroLine.blue,
      latitude: 22.47194,
      longitude: 88.39806,
      layout: 'At grade',
      isInterchange: true,
      connectingLines: [KolkataMetroLine.orange],
      aliases: ['New Garia', 'm_kavi_subhash'],
      popularPandalsNearby: ['New Garia Cooperative', 'Hiland Park Sarbojanin'],
    ),

    // ==========================================
    // --- Line 2: Green Line (East-West Corridor) ---
    // ==========================================
    MetroStation(
      id: 'howrah-maidan',
      name: 'Howrah Maidan',
      nameBn: 'হাওড়া ময়দান',
      code: 'HWMM',
      line: KolkataMetroLine.green,
      latitude: 22.581998,
      longitude: 88.332994,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['m_howrah_maidan'],
      popularPandalsNearby: ['Howrah Sangha', 'Mallick Phatak Pujo'],
    ),
    MetroStation(
      id: 'howrah',
      name: 'Howrah',
      nameBn: 'হাওড়া',
      code: 'HWHM',
      line: KolkataMetroLine.green,
      latitude: 22.584454,
      longitude: 88.340578,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Howrah Railway Station Metro', 'm_howrah_station', 'm_howrah'],
      popularPandalsNearby: ['Howrah Railway Complex Pujo', 'Riverfront Ghats'],
    ),
    MetroStation(
      id: 'mahakaran',
      name: 'Mahakaran',
      nameBn: 'মহাকরণ',
      code: 'MKNA',
      line: KolkataMetroLine.green,
      latitude: 22.571189,
      longitude: 88.350106,
      layout: 'Underground',
      isInterchange: false,
      aliases: ["B.B.D. Bagh", "Writers' Building", 'Lalbazar', 'm_mahakaran'],
      popularPandalsNearby: ["Writers' Building Environs", 'BBD Bagh Heritage Zone'],
    ),
    MetroStation(
      id: 'sealdah',
      name: 'Sealdah',
      nameBn: 'শিয়ালদহ',
      code: 'SDHM',
      line: KolkataMetroLine.green,
      latitude: 22.567207,
      longitude: 88.371497,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['m_sealdah'],
      popularPandalsNearby: ['Sealdah Athletic Club', 'Baithakkhana Sarbojanin'],
    ),
    MetroStation(
      id: 'phoolbagan',
      name: 'Phoolbagan',
      nameBn: 'ফুলবাগান',
      code: 'PBGB',
      line: KolkataMetroLine.green,
      latitude: 22.57214,
      longitude: 88.390282,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['m_phoolbagan'],
      popularPandalsNearby: ['Kankurgachi Mitali Sangha', 'Beleghata Sandhani'],
    ),
    MetroStation(
      id: 'salt-lake-stadium',
      name: 'Salt Lake Stadium',
      nameBn: 'সল্টলেক স্টেডিয়াম',
      code: 'SSSA',
      line: KolkataMetroLine.green,
      latitude: 22.57306,
      longitude: 88.40306,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Yuva Bharati Krirangan', 'm_saltlake_stadium', 'm_salt_lake_stadium'],
      popularPandalsNearby: ['Salt Lake Duttabad', 'Beleghata 33 Pally'],
    ),
    MetroStation(
      id: 'bengal-chemical',
      name: 'Bengal Chemical',
      nameBn: 'বেঙ্গল কেমিক্যাল',
      code: 'BCSD',
      line: KolkataMetroLine.green,
      latitude: 22.580076,
      longitude: 88.401283,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Acharya Prafulla Chandra Ray', 'Mani Square', 'm_bengal_chemical'],
      popularPandalsNearby: ['Mani Square Mall Pujo', 'Kakurgachi Yuba Sammilani'],
    ),
    MetroStation(
      id: 'city-center',
      name: 'City Center',
      nameBn: 'সিটি সেন্টার',
      code: 'CCSC',
      line: KolkataMetroLine.green,
      latitude: 22.587069,
      longitude: 88.407875,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['City Centre Salt Lake', 'm_city_centre', 'm_city_center'],
      popularPandalsNearby: ['Salt Lake Block BJ', 'Salt Lake Block FD'],
    ),
    MetroStation(
      id: 'central-park',
      name: 'Central Park',
      nameBn: 'সেন্ট্রাল পার্ক',
      code: 'CPSA',
      line: KolkataMetroLine.green,
      latitude: 22.590437,
      longitude: 88.415605,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['m_central_park'],
      popularPandalsNearby: ['Salt Lake Mela Ground', 'Salt Lake FD Block'],
    ),
    MetroStation(
      id: 'karunamoyee',
      name: 'Karunamoyee',
      nameBn: 'করুণাময়ী',
      code: 'KESA',
      line: KolkataMetroLine.green,
      latitude: 22.586435,
      longitude: 88.421515,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['m_karunamoyee'],
      popularPandalsNearby: ['Salt Lake AJ Block', 'Salt Lake BJ Block'],
    ),
    MetroStation(
      id: 'salt-lake-sector-v',
      name: 'Salt Lake Sector-V',
      nameBn: 'সল্টলেক সেক্টর V',
      code: 'SVSA',
      line: KolkataMetroLine.green,
      latitude: 22.581318,
      longitude: 88.429822,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Sector V', 'm_sector_v', 'm_salt_lake_sector_v'],
      popularPandalsNearby: ['College More Technology Hub', 'New Town Gateway'],
    ),

    // ==========================================
    // --- Line 3: Purple Line (Joka-Esplanade Corridor) ---
    // ==========================================
    MetroStation(
      id: 'joka',
      name: 'Joka',
      nameBn: 'জোকা',
      code: 'KJKA',
      line: KolkataMetroLine.purple,
      latitude: 22.452244,
      longitude: 88.301751,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Diamond Park', 'm_joka'],
      popularPandalsNearby: ['Joka Sarbojanin', 'Diamond Park Pujo'],
    ),
    MetroStation(
      id: 'thakurpukur',
      name: 'Thakurpukur',
      nameBn: 'ঠাকুরপুকুর',
      code: 'KTKP',
      line: KolkataMetroLine.purple,
      latitude: 22.464261,
      longitude: 88.307555,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['m_thakurpukur'],
      popularPandalsNearby: ['Thakurpukur SB Park', 'Bhadrakali Sarbojanin'],
    ),
    MetroStation(
      id: 'behala-sakherbazar',
      name: 'Behala Sakherbazar',
      nameBn: 'সখেরবাজার',
      code: 'KSKB',
      line: KolkataMetroLine.purple,
      latitude: 22.474611,
      longitude: 88.309991,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Silpara', 'Sakherbazar', 'm_behala_sakherbazar'],
      popularPandalsNearby: ['Silpara Sarbojanin', 'Sakherbazar Pujo'],
    ),
    MetroStation(
      id: 'behala-chowrasta',
      name: 'Behala Chowrasta',
      nameBn: 'বেহালা চৌরাস্তা',
      code: 'KBCR',
      line: KolkataMetroLine.purple,
      latitude: 22.487529,
      longitude: 88.313426,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Chowrasta', 'm_behala_chowrasta'],
      popularPandalsNearby: ['Behala Nutan Dal', 'Barisha Club', 'Behala Friends'],
    ),
    MetroStation(
      id: 'behala-bazar',
      name: 'Behala Bazar',
      nameBn: 'বেহালা বাজার',
      code: 'KBBR',
      line: KolkataMetroLine.purple,
      latitude: 22.498929,
      longitude: 88.317354,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Behala Market', 'm_behala_bazar'],
      popularPandalsNearby: ['Behala Club', 'Behala Buroshibtala'],
    ),
    MetroStation(
      id: 'taratala',
      name: 'Taratala',
      nameBn: 'তারাতলা',
      code: 'KTRT',
      line: KolkataMetroLine.purple,
      latitude: 22.508165,
      longitude: 88.320563,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Pathakpara', 'm_taratala'],
      popularPandalsNearby: ['Taratala Sarbojanin', 'Sahapur Durgotsab'],
    ),
    MetroStation(
      id: 'majerhat',
      name: 'Majerhat',
      nameBn: 'মাঝেরহাট',
      code: 'KMJH',
      line: KolkataMetroLine.purple,
      latitude: 22.5191,
      longitude: 88.3234,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['m_majerhat'],
      popularPandalsNearby: ['Alipore Mint', 'Chetla Agrani (West Entry)'],
    ),

    // ==========================================
    // --- Line 6: Orange Line (New Garia-Airport Corridor) ---
    // ==========================================
    MetroStation(
      id: 'satyajit-ray',
      name: 'Satyajit Ray',
      nameBn: 'সত্যজিৎ রায়',
      code: 'KSJR',
      line: KolkataMetroLine.orange,
      latitude: 22.4846,
      longitude: 88.3926,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Chak Garia', 'Ajoy Nagar', 'm_satyajit_ray'],
      popularPandalsNearby: ['Peerless Hospital Area Pujo', 'Ajoy Nagar Durgotsav'],
    ),
    MetroStation(
      id: 'jyotirindra-nandi',
      name: 'Jyotirindra Nandi',
      nameBn: 'জ্যোতিরিন্দ্র নন্দী',
      code: 'KJNN',
      line: KolkataMetroLine.orange,
      latitude: 22.495915,
      longitude: 88.398667,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Singhbari', 'm_jyotirindra_nandi'],
      popularPandalsNearby: ['Mukundapur Sarbojanin', 'Santoshpur Lake Pally (East Entry)'],
    ),
    MetroStation(
      id: 'kavi-sukanta',
      name: 'Kavi Sukanta',
      nameBn: 'কবি সুকান্ত',
      code: 'KKSK',
      line: KolkataMetroLine.orange,
      latitude: 22.505262,
      longitude: 88.400996,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Avishikta More', 'Kalikapur', 'm_kavi_sukanta'],
      popularPandalsNearby: ['Kalikapur Sarbojanin', 'Haltu Naba Sarathi'],
    ),
    MetroStation(
      id: 'hemanta-mukhopadhyay',
      name: 'Hemanta Mukhopadhyay',
      nameBn: 'হেমন্ত মুখোপাধ্যায়',
      code: 'KHMD',
      line: KolkataMetroLine.orange,
      latitude: 22.514777,
      longitude: 88.401469,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Ruby More', 'Ruby Hospital', 'm_hemanta_mukhopadhyay'],
      popularPandalsNearby: ['Ruby Hospital Crossing', 'Kasba Bosepukur Sitala Mandir'],
    ),
    MetroStation(
      id: 'vip-bazar',
      name: 'VIP Bazar',
      nameBn: 'ভিআইপি বাজার',
      code: 'KVIB',
      line: KolkataMetroLine.orange,
      latitude: 22.5255,
      longitude: 88.39586,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['m_vip_bazar'],
      popularPandalsNearby: ['VIP Bazar Sarbojanin', 'Tagore Park Pujo'],
    ),
    MetroStation(
      id: 'ritwik-ghatak',
      name: 'Ritwik Ghatak',
      nameBn: 'ঋত্বিক ঘটক',
      code: 'KRWG',
      line: KolkataMetroLine.orange,
      latitude: 22.5328605,
      longitude: 88.3957647,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Bantala Road', 'Uttar Panchanagram', 'Topsia', 'm_ritwik_ghatak'],
      popularPandalsNearby: ['Topsia Sarbojanin', 'Panchanagram Pujo'],
    ),
    MetroStation(
      id: 'barun-sengupta',
      name: 'Barun Sengupta',
      nameBn: 'বরুণ সেনগুপ্ত',
      code: 'KBST',
      line: KolkataMetroLine.orange,
      latitude: 22.54393,
      longitude: 88.40015,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Science City', 'Dhapa', 'Mathpukur', 'm_barun_sengupta'],
      popularPandalsNearby: ['Science City Ground', 'Dhapa Sarbojanin'],
    ),
    MetroStation(
      id: 'beleghata',
      name: 'Beleghata',
      nameBn: 'বেলেঘাটা',
      code: 'KBGA',
      line: KolkataMetroLine.orange,
      latitude: 22.550703,
      longitude: 88.404094,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['Metropolitan', 'm_beleghata'],
      popularPandalsNearby: ['Metropolitan Durgotsav', 'Chingrighata Sarbojanin'],
    ),

    // ==========================================
    // --- Line 4: Yellow Line (Noapara-Airport Corridor) ---
    // ==========================================
    MetroStation(
      id: 'dum-dum-cantonment',
      name: 'Dum Dum Cantonment',
      nameBn: 'দমদম ক্যান্টনমেন্ট',
      code: 'KDCM',
      line: KolkataMetroLine.yellow,
      latitude: 22.638,
      longitude: 88.4123,
      layout: 'Elevated',
      isInterchange: false,
      aliases: ['m_dum_dum_cantonment'],
      popularPandalsNearby: ['Cantonment Sarbojanin', 'Subhas Nagar Club'],
    ),
    MetroStation(
      id: 'jessore-road',
      name: 'Jessore Road',
      nameBn: 'যশোহর রোড',
      code: 'KJRO',
      line: KolkataMetroLine.yellow,
      latitude: 22.6395137,
      longitude: 88.4297765,
      layout: 'At grade',
      isInterchange: false,
      aliases: ['m_jessore_road'],
      popularPandalsNearby: ['Jessore Road Sarbojanin', 'Nagerbazar Crossing Area'],
    ),
    MetroStation(
      id: 'jai-hind',
      name: 'Jai Hind',
      nameBn: 'জয় হিন্দ',
      code: 'KJHD',
      line: KolkataMetroLine.yellow,
      latitude: 22.64619,
      longitude: 88.43591,
      layout: 'Underground',
      isInterchange: false,
      aliases: ['Biman Bandar', 'Airport', 'Kolkata Airport', 'm_jai_hind'],
      popularPandalsNearby: ['NSCB International Airport Terminal Zone'],
    ),
  ];

  /// Sequential station IDs for each line in geometric/transit order.
  static const Map<KolkataMetroLine, List<String>> lineStationSequences = {
    KolkataMetroLine.blue: [
      'dakshineswar',
      'baranagar',
      'noapara',
      'dum-dum',
      'belgachhia',
      'shyambazar',
      'shobhabazar-sutanuti',
      'girish-park',
      'mahatma-gandhi-road',
      'central',
      'chandni-chowk',
      'esplanade',
      'park-street',
      'maidan',
      'rabindra-sadan',
      'netaji-bhavan',
      'jatin-das-park',
      'kalighat',
      'rabindra-sarobar',
      'mahanayak-uttam-kumar',
      'netaji',
      'masterda-surya-sen',
      'gitanjali',
      'kavi-nazrul',
      'shahid-khudiram',
      'kavi-subhash',
    ],
    KolkataMetroLine.green: [
      'howrah-maidan',
      'howrah',
      'mahakaran',
      'esplanade',
      'sealdah',
      'phoolbagan',
      'salt-lake-stadium',
      'bengal-chemical',
      'city-center',
      'central-park',
      'karunamoyee',
      'salt-lake-sector-v',
    ],
    KolkataMetroLine.purple: [
      'joka',
      'thakurpukur',
      'behala-sakherbazar',
      'behala-chowrasta',
      'behala-bazar',
      'taratala',
      'majerhat',
    ],
    KolkataMetroLine.orange: [
      'kavi-subhash',
      'satyajit-ray',
      'jyotirindra-nandi',
      'kavi-sukanta',
      'hemanta-mukhopadhyay',
      'vip-bazar',
      'ritwik-ghatak',
      'barun-sengupta',
      'beleghata',
    ],
    KolkataMetroLine.yellow: [
      'noapara',
      'dum-dum-cantonment',
      'jessore-road',
      'jai-hind',
    ],
  };

  /// Returns ordered station list for a specific line in transit direction.
  static List<MetroStation> getStationsForLine(KolkataMetroLine line) {
    final sequence = lineStationSequences[line] ?? [];
    final stationMap = {for (final s in allStations) s.id: s};
    return sequence.map((id) => stationMap[id]).whereType<MetroStation>().toList();
  }

  /// Station lookup by id, alias, or legacy ID.
  static MetroStation? findById(String id) {
    for (final s in allStations) {
      if (s.matchesId(id)) return s;
    }
    return null;
  }

  /// Geographic track line coordinates for each of the 5 metro lines.
  static Map<KolkataMetroLine, List<LatLng>> get lineTrackCoordinates {
    final map = <KolkataMetroLine, List<LatLng>>{};
    for (final line in KolkataMetroLine.values) {
      final stations = getStationsForLine(line);
      map[line] = stations.map((s) => s.toLatLng()).toList();
    }
    return map;
  }

  /// Searches metro stations matching query text (name, Bengali name, line, or nearby pandals).
  List<MetroStation> searchStations(String query) {
    if (query.trim().isEmpty) return allStations;
    final clean = query.trim().toLowerCase();
    return allStations.where((s) {
      final name = s.name.toLowerCase();
      final nameBn = s.nameBn?.toLowerCase() ?? '';
      final code = s.code?.toLowerCase() ?? '';
      final lineName = s.line.label.toLowerCase();
      final aliasMatch = s.aliases.any((a) => a.toLowerCase().contains(clean));
      final nearby = s.popularPandalsNearby.any((p) => p.toLowerCase().contains(clean));
      return name.contains(clean) ||
          nameBn.contains(clean) ||
          code.contains(clean) ||
          lineName.contains(clean) ||
          aliasMatch ||
          nearby;
    }).toList();
  }
}
